# Generated by Django 3.1.7 on 2021-02-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=256)),
                ('tag_category', models.CharField(choices=[('COPYRIGHT', 'COPYRIGHT'), ('CHARACTER', 'CHARACTER'), ('ARTIST', 'ARTIST'), ('METADATA', 'METADATA'), ('GENERAL', 'GENERAL')], default='GENERAL', max_length=256)),
                ('auto_deny', models.BooleanField(default=False)),
                ('tag_notes', models.TextField()),
            ],
        ),
    ]
