# Generated by Django 3.1.7 on 2021-02-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_auto_20210226_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
