# Generated by Django 3.1.7 on 2021-02-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_post_imported_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
