# Generated by Django 3.1.7 on 2021-02-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0008_tag_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_height',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_width',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.IntegerField(default=-1),
        ),
    ]
