# Generated by Django 3.1.7 on 2021-02-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0010_auto_20210227_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='import_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
