# Generated by Django 3.1.7 on 2021-02-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0011_post_import_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='import_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
