# Generated by Django 3.1.7 on 2021-03-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0013_auto_20210228_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shimmie_tag',
            field=models.IntegerField(default=-1),
        ),
    ]
