# Generated by Django 3.1.7 on 2021-03-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0014_post_shimmie_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='shimmie_tag',
            new_name='shimmie_id',
        ),
    ]
